### ISSUE TITLE
Update Models

### ISSUE THREAD

**Issue by AesaKamar** [AesaKamar/Pokedex#5]
Update model for Pokemon in "/app/models/pokemons_controller.rb"

Create model for Abilities
Create model for Moves
Use command "rails generate scaffold <name> <[attributes]>" to make new models, views, migrations, and controllers all in one!

Check with "/DBSchema.xlsx"  to know what fields need to be in the relation

**Comment by MonkStrom** [comment]
pokemons_controller.rb found in "/app/controllers/"
"app/models/" has pokemon.rb
